### ISSUE TITLE
fcntl does not exist on windows

### ISSUE THREAD

**Issue by solvingj** [codrsquad/runez#5]
Trying to use `portable-python` which depends on `runez` and get the error below.  

`ModuleNotFoundError: No module named 'fcntl'`

> The fcntl module is not available on Windows. The functionality it exposes does not exist on that platform.

https://stackoverflow.com/questions/45228395/error-no-module-named-fcntl

```

portable-python build 3.10.4
Traceback (most recent call last):
  File "C:\tools\python\versions\3.8.1\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\tools\python\versions\3.8.1\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\build\.venv\portable_python_venv_windows\Scripts\portable-python.EXE\__main__.py", line 5, in <module>
  File "C:\build\.venv\portable_python_venv_windows\lib\site-packages\portable_python\__init__.py", line 19, in <module>
    import runez
  File "C:\build\.venv\portable_python_venv_windows\lib\site-packages\runez\__init__.py", line 5, in <module>
    from runez import ascii, click, config, date, file, program, serialize, system
  File "C:\build\.venv\portable_python_venv_windows\lib\site-packages\runez\program.py", line 6, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

**Comment by zsimic** [comment]
That's used in `runez.run(..., passthrough=True)`, where output of a command is both captured and "passed through" to stdout/stderr

**Comment by solvingj** [comment]
Ok,  `runez` currently not supported on Windows.  Got it, thanks!
